### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by ever4cyth** [haddocking/disvis#2]
Hi developer,

wonder how to generate figure 1 in your paper? Any script to do that? Thanks!

**Comment by latrocinia** [comment]
Hi,
For the figure we used UCSF Chimera, no special script. After running disvis, we opened the fixed and scanning chain, together with the output accessible_interaction_space.mrc. This shows then the spaces that are consistent with at least N restraints, where N can be chosen by using the density slider in Chimera. 
Hope this helps!
Gydo
On Jun 8, 2015 5:43 AM, ever4cyth notifications@github.com wrote:Hi developer,

wonder how to generate figure 1 in your paper? Any script to do that? Thanks!

**Comment by amjjbonvin** [comment]
May-be good to add this info to the repo

---

Dr. Alexandre M.J.J Bonvin 
Professor of Computational Structural Biology
Faculty of Science, Utrecht University, the Netherlands
Phone: +31-30-2533859   |   Fax: +31-30-2537623
Email: a.m.j.j.bonvin@uu.nl 

## http://www.uu.nl/staff/amjjbonvin  | http://bonvinlab.org
