### ISSUE TITLE
Incorrect selection of restrained atoms

### ISSUE THREAD

**Issue by schaarj** [haddocking/disvis#8]

**Comment by latrocinia** [comment]
This issue can be closed?

**Comment by amjjbonvin** [comment]
Has it been solved? Is there a commit associated with it? If yes then can be closed, but the commit number should be added as comment, e.g.: Issue solved by commit ...

**Comment by mtrellet** [comment]
Yes it has been solved by issue #9, a mix of issue references back then I guess. @schaarj do you confirm we can close that?

**Comment by schaarj** [comment]
yes PR #9 solved the issue if I'm not mistaken!
